# Default values for cocolit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

streamlit:
  replicaCount:  1
  image:
    repository: ghcr.io/davnish/streamlit-server
    tag: 3e7d5d0
  service:
    ports: 8501

inference:
  replicaCount: 1
  image:
    repository: ghcr.io/davnish/inference-server 
    tag: 3e7d5d0
  service:
    ports: 8000



# service

streamlitService:
  selector:
    app: streamlit-server
  ports:
    port: 80
    targetPort: 8501
    type: ClusterIP
    
inferenceService:
  selector:
    app: inference-server
  ports:
    port: 80
    targetPort: 8000
    type: ClusterIP

# clusterissuer
clusterIssuer:
  name: letsencrypt-prod
  email: nischal.singh38@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  ingressClass: traefik

# Ingress
ingress:
  enabled: true
  name: streamlit-ingress
  className: traefik
  host: cocolit.prithvilabs.com
  serviceName: cocolit-streamlit-service
  servicePort: 80
  tlsSecret: streamlit-tls
  clusterIssuer: letsencrypt-prod
