FROM mambaorg/micromamba:1.5.1

ARG MAMBA_DOCKERFILE_ACTIVATE=1

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

RUN micromamba install -c conda-forge \
    python=3.9 \
    gdal==3.2.2 \
    pip \
    -y

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir uv && \
    uv pip install --no-cache-dir -r requirements.txt --system && \
    uv pip install --no-cache-dir pytest --system

COPY src /app/src
COPY test /app/test
COPY pipelines /app/pipelines
COPY models /app/models
COPY pyproject.toml /app/
COPY configs /app/configs

ENTRYPOINT [ "/usr/local/bin/_entrypoint.sh", "pytest"  ]
