FROM python:3.11-slim-bullseye

LABEL org.opencontainers.image.source = "https://github.com/davnish/cocolit"

USER root

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /app

COPY packages.txt /app/packages.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    $(grep -vE '^\s*#|^\s*$' /app/packages.txt) \
    gcc \
    g++ \
    && apt-get purge -y --auto-remove \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir --no-build-isolation numpy
RUN pip install --upgrade pip setuptools wheel cython
RUN pip install --no-cache-dir --no-build-isolation -r requirements.txt 

RUN pip install --no-cache-dir pytest 

COPY pyproject.toml /app/
COPY src /app/src
COPY tests /app/tests
COPY pipelines /app/pipelines
COPY models /app/models
COPY configs /app/configs

ENTRYPOINT [ "pytest" ]
