FROM mambaorg/micromamba:1.5.1

USER root

ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

RUN micromamba install -c conda-forge \
    python=3.9 \
    gdal==3.2.2 \
    pip \
    -y


WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir uv

RUN uv pip install --no-cache-dir -r requirements.txt --system

RUN uv pip install --no-cache-dir  pytest --system

ENTRYPOINT [ "micromamba", "run", "-n", "base", "pytest"  ]
