site_name: My Docs
site_url: https://github.com/davnish/cocolit.git

theme:
  name: material


repo_name: davnish/rasvec
repo_url: https://github.com/davnish/rasvec

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg