[project]
name = "cocolit"
version = "0.1.0"
description = "lets detect some coconuts!"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
