apiVersion: batch/v1
kind: Job
metadata:
  name: cocolit-db-init
  namespace: apps
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: db-init
        image: ghcr.io/davnish/streamlit-server:2c6a521
        command: ["python", "-m", "src.database.init_db"]

        env:
        - name: POSTGRES_HOST
          value: postgis-cluster-rw

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username

        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: database
              
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password

      restartPolicy: Never