auth:
  existingSecret: postgres-credentials
  username: cocolit_user
  database: cocolitdb
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  initdb:
    scripts:
      install_postgis.sh: |
        apt-get update
        apt-get install -y postgis postgresql-16-postgis-3
      enable_postgis.sql: |
        CREATE EXTENSION IF NOT EXISTS postgis;