auth:
  existingSecret: postgres-credentials
  username: cocolit_user
  database: cocolitdb
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16

postgresqlSharedPreloadLibraries: "postgis"

primary:
  initdb:
    scripts:
      postgis.sql: |
        CREATE EXTENSION IF NOT EXISTS postgis;