auth:
  existingSecret: postgres-credentials
  username: cocolit_user
  database: cocolitdb
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

image:
  repository: postgis/postgis
  tag: 16-3.4
  pullPolicy: IfNotPresent

primary:
  initdb:
    scripts:
      00_postgis.sql: |
        CREATE EXTENSION IF NOT EXISTS postgis;
        CREATE EXTENSION IF NOT EXISTS postgis_topology;
