path: ../CocoDet/data/test_dataset # dataset root dir
train: train/images # train images (relative to 'path') 4 images
val: val/images # val images (relative to 'path') 4 images
test: test/images


names:
    0: coconut_tree
