apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password }}
  postgres-user: {{ .Values.postgres.user }}
  postgres-database: {{ .Values.postgres.database }}