apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  postgres-password: {{ .Values.database.postgresPassword }}
  POSTGRESQL_USERNAME: {{ .Values.database.username }}
  POSTGRESQL_PASSWORD: {{ .Values.database.password }}
  POSTGRESQL_DATABASE: {{ .Values.database.database }}