apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  postgres-password: {{ .Values.database.postgresPassword }}
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
  database: {{ .Values.database.database }}