apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
stringData:
  SMTP_FROMADDR: {{ .Values.smtp.from }}
  SMTP_TOADDRS: {{ .Values.smtp.to }}
  SMTP_USERNAME: {{ .Values.smtp.username }}
  SMTP_PASSWORD: {{ .Values.smtp.password }}