apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cocolit.fullname" . }}-streamlit-deployment
  labels:
    project: cocolit
spec:
  replicas: {{ .Values.streamlit.replicaCount }}
  selector:
    matchLabels:
      app: streamlit-server
  template:
    metadata:
      labels:
        app: streamlit-server
    spec:
      containers:
      - name: streamlit-server
        image: "{{ .Values.streamlit.image.repository }}:{{ .Values.streamlit.image.tag }}"
        ports:
        - containerPort: 8501
        
        env:
        - name: INFERENCE_URL
          value: "http://cocolit-inference-service/predict" 

        - name: POSTGRES_HOST
          value: {{ .Values.database.host }}

        - name: POSTGRES_USERNAME
          value: {{ .Values.database.username }}

        - name: POSTGRES_DATABASE
          value: {{ .Values.database.database }}
              
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password

        envFrom:
        - secretRef:
            name: smtp-credentials