apiVersion: v1
kind: Service
metadata:
  name: {{ include "cocolit.fullname" . }}-streamlit-service
spec:
  selector:
    app: {{ .Values.inferenceService.selector.app }} 
  ports:
    - port: {{ .Values.inferenceService.ports.port }}         # Port exposed to the Ingress
      targetPort: {{ .Values.inferenceService.ports.targetPort }} # Port Streamlit is running on
  type: {{ .Values.inferenceService.type }}
