name: Build and Deploy Streamlit

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ci_cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # Short SHA for tagging
    - name: Set short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    # Login to GHCR
    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build docker image
    - name: Build Streamlit Image
      run: |
        docker build \
          -t ghcr.io/davnish/streamlit-server:${{ env.SHORT_SHA }} \
          -f streamlit.Dockerfile .

    # Push docker image
    - name: Push Docker Image
      run: |
        docker push ghcr.io/davnish/streamlit-server:${{ env.SHORT_SHA }}

    # Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    # Install Helm
    - name: Install Helm
      uses: azure/setup-helm@v4

    # Configure kubeconfig
    - name: Setup kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # Test cluster connectivity
    - name: Verify cluster access
      run: kubectl get nodes

    # Deploy using Helm
    - name: Deploy Helm Chart
      run: |
        helm upgrade --install cocolit ./charts/cocolit \
          --namespace apps \
          --create-namespace \
          --set streamlit.image.tag=${{ env.SHORT_SHA }}